#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="${REPO_ROOT:-/data/home/grads/jflashner/CounterBMT_run}"
PYTHONPATH="${PYTHONPATH:-/data/home/grads/jflashner/CounterBMT/metadrive:$REPO_ROOT/scenarionet:$REPO_ROOT/src/Adv-BMT}"
PYTHON_BIN="${PYTHON_BIN:-}"

# By default reserve GPU 3 for the sidecar SADE evaluator.
CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2}"
DEVICES="${DEVICES:-3}"

INDEX_ROOT="${INDEX_ROOT:-/data/home/grads/jflashner/CounterBMT_run/outputs/pr10_1_sdc_semantic_top500_from859}"
DATA_ROOT="${DATA_ROOT:-/data/home/grads/jflashner/CounterBMT/outputs/pr10_1_sdc_semantic_top859_full/scenario_root}"
TRAIN_INDEX="${TRAIN_INDEX:-$INDEX_ROOT/sdc_semantic_control_index_train_factual_gt.jsonl}"
VAL_INDEX="${VAL_INDEX:-$INDEX_ROOT/sdc_semantic_control_index_val_factual_gt.jsonl}"
PAPER_REALISM_INDEX="${PAPER_REALISM_INDEX:-$VAL_INDEX}"

TEACHER_CKPT="${TEACHER_CKPT:-$REPO_ROOT/src/Adv-BMT/bmt/ckpt/last.ckpt}"
PRETRAIN_CKPT="${PRETRAIN_CKPT:-/data/home/grads/jflashner/CounterBMT_run/logs/nointervention_gtce_only_top859_waymo_runs/pr10_1_waymo3394_waymax687_nointervention_gtce_only_from_step200_bs16_nocallback_4gpu_a100_zh1_run2/lightning_logs/infgen/pr10_1_waymo3394_waymax687_nointervention_gtce_only_from_step200_bs16_nocallback_4gpu_a100_zh1_run2_2026-04-24/checkpoints/pr10_1_waymo3394_waymax687_nointervention_gtce_only_from_step200_bs16_nocallback_4gpu_a100_zh1_run2_2026-04-24_epoch=13-step=800.ckpt}"
RESUME_CKPT="${RESUME_CKPT:-}"
if [[ "$PRETRAIN_CKPT" == "none" || "$PRETRAIN_CKPT" == "NONE" || "$PRETRAIN_CKPT" == "__NONE__" ]]; then
  PRETRAIN_CKPT=""
fi

RUN_GROUP_ROOT="${RUN_GROUP_ROOT:-/data/home/grads/jflashner/CounterBMT_run/logs/factualgt_semantic_ce_repair_runs}"
EXP_NAME="${EXP_NAME:-pr10_1_top500_factualgt_semantic_ce_from_step800_bs16_3gpu_a100_zh1_run1}"
OUTDIR="${OUTDIR:-$RUN_GROUP_ROOT/$EXP_NAME}"

MAX_STEPS="${MAX_STEPS:-2000}"
VAL_INTERVAL="${VAL_INTERVAL:-200}"
SEED="${SEED:-0}"
CKPT_LOAD_MODE="${CKPT_LOAD_MODE:-forgiving_state_dict}"
WANDB_ENABLED="${WANDB_ENABLED:-true}"
LR="${LR:-0.00005}"
WARMUP_STEPS="${WARMUP_STEPS:-100}"
ACCUMULATE_GRAD_BATCHES="${ACCUMULATE_GRAD_BATCHES:-1}"
BATCH_SIZE="${BATCH_SIZE:-16}"
VAL_BATCH_SIZE="${VAL_BATCH_SIZE:-8}"
NUM_WORKERS="${NUM_WORKERS:-8}"
VAL_NUM_WORKERS="${VAL_NUM_WORKERS:-4}"
NUM_SANITY_VAL_STEPS="${NUM_SANITY_VAL_STEPS:-0}"
LIMIT_VAL_BATCHES="${LIMIT_VAL_BATCHES:-1}"
CHECKPOINT_EVERY_N_EPOCHS="${CHECKPOINT_EVERY_N_EPOCHS:-10}"
CHECKPOINT_SAVE_TOP_K="${CHECKPOINT_SAVE_TOP_K:--1}"

ROLLOUT_TRAIN_DEBUG_ENABLED="${ROLLOUT_TRAIN_DEBUG_ENABLED:-false}"
PAPER_REALISM_EVAL_ENABLED="${PAPER_REALISM_EVAL_ENABLED:-false}"
PAPER_REALISM_EVAL_EVERY_N_VALIDATIONS="${PAPER_REALISM_EVAL_EVERY_N_VALIDATIONS:-1}"
PAPER_REALISM_EVAL_LIMIT_BATCHES="${PAPER_REALISM_EVAL_LIMIT_BATCHES:-50}"
PAPER_REALISM_EVAL_DEVICE="${PAPER_REALISM_EVAL_DEVICE:-cpu}"
EXTRA_ARGS="${EXTRA_ARGS:-}"

mkdir -p "$OUTDIR"

cd "$REPO_ROOT"
export PYTHONPATH
export CUDA_VISIBLE_DEVICES
export TORCH_NCCL_ASYNC_ERROR_HANDLING=1
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"

if [[ -z "$PYTHON_BIN" ]]; then
  for candidate in \
    "$REPO_ROOT/.venv-legacy-adv-bmt/bin/python" \
    "/data/home/grads/jflashner/CounterBMT/.venv-legacy-adv-bmt/bin/python" \
    "$REPO_ROOT/.venv/bin/python" \
    "/data/home/grads/jflashner/CounterBMT/.venv/bin/python"
  do
    if [[ -x "$candidate" ]]; then
      PYTHON_BIN="$candidate"
      break
    fi
  done
fi
if [[ -z "$PYTHON_BIN" ]]; then
  PYTHON_BIN="$(command -v python3)"
fi

cmd=(
  "$PYTHON_BIN"
  src/Adv-BMT/bmt/train_motion.py
  --config-name
  motion_forward_sdc_semantic_only_strict_local.yaml
  exp_name="$EXP_NAME"
  DATA.TRAINING_DATA_DIR="$DATA_ROOT"
  DATA.TEST_DATA_DIR="$DATA_ROOT"
  DATA.COUNTERFACTUAL_CONTROL_INDEX_TRAIN="$TRAIN_INDEX"
  DATA.COUNTERFACTUAL_CONTROL_INDEX_VAL="$VAL_INDEX"
  DATA.COUNTERFACTUAL_MODE="sdc_semantic_only"
  DATA.COUNTERFACTUAL_ALT_ONLY_TRAIN=false
  DATA.COUNTERFACTUAL_WEIGHTED_SAMPLER=false
  ++DATA.DROP_ORIGINAL_SD_IN_BATCH=true
  ++DATA.COUNTERFACTUAL_SEMANTIC_RL_INCLUDE_GT_ROWS=true
  batch_size="$BATCH_SIZE"
  val_batch_size="$VAL_BATCH_SIZE"
  num_workers="$NUM_WORKERS"
  val_num_workers="$VAL_NUM_WORKERS"
  num_sanity_val_steps="$NUM_SANITY_VAL_STEPS"
  epochs=240
  CKPT_LOAD_MODE="$CKPT_LOAD_MODE"
  OPTIMIZATION.LR="$LR"
  OPTIMIZATION.WARMUP_STEPS="$WARMUP_STEPS"
  MODEL.LOCAL_CONTROL_SDC_POLICY_TEACHER_CKPT="$TEACHER_CKPT"
  MODEL.LOCAL_CONTROL_NULL_DROPOUT_PROB=0.0
  MODEL.LOCAL_CONTROL_SDC_STEM_LOSS_WEIGHT=0.0
  MODEL.LOCAL_CONTROL_SDC_FAMILY_GUIDE_LOSS_WEIGHT=0.0
  MODEL.LOCAL_CONTROL_SDC_ROLLOUT_GUIDE_LOSS_WEIGHT=0.0
  MODEL.LOCAL_CONTROL_SDC_ROLLOUT_PROGRESS_LOSS_WEIGHT=0.0
  MODEL.LOCAL_CONTROL_SDC_SEMANTIC_AUX_LOSS_WEIGHT=0.0
  MODEL.LOCAL_CONTROL_SDC_ROLLOUT_TUBE_POLICY_LOSS_WEIGHT=0.0
  MODEL.LOCAL_CONTROL_SDC_ROLLOUT_TUBE_GROUP_SIZE=1
  MODEL.LOCAL_CONTROL_TRAIN_OUTPUT_HEAD=true
  MODEL.LOCAL_CONTROL_TRAIN_LAST_N_DECODER_BLOCKS=6
  MODEL.LOCAL_CONTROL_GRAD_CLIP_NORM=5.0
  ++MODEL.LOCAL_CONTROL_SDC_SEMANTIC_EXT_ENABLED=true
  ++MODEL.LOCAL_CONTROL_SDC_SEMANTIC_EXT_ALLOW_PROGRESS_REWARD=false
  ++MODEL.LOCAL_CONTROL_SDC_SEMANTIC_EXT_KL_WEIGHT_GT=0.0
  ++MODEL.LOCAL_CONTROL_SDC_SEMANTIC_EXT_KL_WEIGHT_ALT=0.0
  ++MODEL.LOCAL_CONTROL_SDC_SEMANTIC_EXT_STALL_WEIGHT=0.0
  ++MODEL.LOCAL_CONTROL_SDC_SEMANTIC_EXT_CENTER_WEIGHT_MAX=0.0
  ++MODEL.LOCAL_CONTROL_SDC_SEMANTIC_EXT_TRAFFIC_SPEED_FLOOR_ENABLED=false
  ++MODEL.LOCAL_CONTROL_SDC_SEMANTIC_EXT_TRAFFIC_SPEED_CAP_ENABLED=false
  ++MODEL.LOCAL_CONTROL_SDC_SEMANTIC_EXT_BEHAVIOR_MODEL_ENABLED=false
  ++MODEL.LOCAL_CONTROL_SDC_SEMANTIC_EXT_CONSENSUS_WEIGHT=0.0
  ++MODEL.LOCAL_CONTROL_SDC_SEMANTIC_EXT_NOVELTY_ENABLED=false
  ++MODEL.LOCAL_CONTROL_SDC_SEMANTIC_EXT_THERMOSTAT_ENABLED=false
  +devices="$DEVICES"
  +max_steps="$MAX_STEPS"
  +val_interval="$VAL_INTERVAL"
  +checkpoint_every_n_epochs="$CHECKPOINT_EVERY_N_EPOCHS"
  +checkpoint_save_top_k="$CHECKPOINT_SAVE_TOP_K"
  limit_val_batches="$LIMIT_VAL_BATCHES"
  accumulate_grad_batches="$ACCUMULATE_GRAD_BATCHES"
  log_dir="$OUTDIR"
  seed="$SEED"
  wandb="$WANDB_ENABLED"
  ROLLOUT_TRAIN_DEBUG_ENABLED="$ROLLOUT_TRAIN_DEBUG_ENABLED"
  ROLLOUT_TRAIN_DEBUG_EVERY_N_STEPS=100000
  ROLLOUT_TRAIN_DEBUG_MAX_MATCHES=0
  ROLLOUT_TRAIN_DEBUG_SCENARIO_IDS=[]
  PAPER_REALISM_EVAL_ENABLED="$PAPER_REALISM_EVAL_ENABLED"
  PAPER_REALISM_EVAL_EVERY_N_VALIDATIONS="$PAPER_REALISM_EVAL_EVERY_N_VALIDATIONS"
  PAPER_REALISM_EVAL_CONTROL_INDEX="$PAPER_REALISM_INDEX"
  PAPER_REALISM_EVAL_DATA_DIR="$DATA_ROOT"
  PAPER_REALISM_EVAL_LIMIT_BATCHES="$PAPER_REALISM_EVAL_LIMIT_BATCHES"
  PAPER_REALISM_EVAL_DEVICE="$PAPER_REALISM_EVAL_DEVICE"
)

if [[ -n "$PRETRAIN_CKPT" ]]; then
  cmd+=(pretrain="'$PRETRAIN_CKPT'")
fi

if [[ -n "$RESUME_CKPT" ]]; then
  cmd+=(ckpt="'$RESUME_CKPT'")
fi

if [[ -n "$EXTRA_ARGS" ]]; then
  read -r -a extra_args <<< "$EXTRA_ARGS"
  cmd+=("${extra_args[@]}")
fi

"${cmd[@]}"
