#!/usr/bin/env python3
"""
CounterBMT Scenario Replay Script

Auto-generated script to replay counterfactual scenarios in MetaDrive.

Usage:
    python replay_scenarios.py
    python replay_scenarios.py --scenario 0  # Replay specific scenario
    python replay_scenarios.py --render      # With rendering

Requirements:
    - MetaDrive installed
    - ScenarioNet data
"""

import argparse
import pickle
from pathlib import Path

# Scenario files generated by CounterBMT
SCENARIO_FILES = [
    "outputs/counterbmt_pipeline/473727ed71e9d699/replay_scenarios/sd_counterfactual_1.0_473727ed71e9d699_cf_0_Set_Ego_Initial_Speed_to_3_294.pkl",
    "outputs/counterbmt_pipeline/473727ed71e9d699/replay_scenarios/sd_counterfactual_1.0_473727ed71e9d699_cf_1_Set_Ego_Initial_Speed_to_4_942.pkl",
    "outputs/counterbmt_pipeline/473727ed71e9d699/replay_scenarios/sd_counterfactual_1.0_473727ed71e9d699_cf_2_Set_Ego_Initial_Speed_to_8_236.pkl",
    "outputs/counterbmt_pipeline/473727ed71e9d699/replay_scenarios/sd_counterfactual_1.0_473727ed71e9d699_cf_3_Set_Maneuver__straight_to_stop.pkl",
    "outputs/counterbmt_pipeline/473727ed71e9d699/replay_scenarios/sd_counterfactual_1.0_473727ed71e9d699_cf_4_Set_Maneuver__lane_change_left.pkl",
]

def load_scenario(path):
    """Load a scenario from pickle file."""
    with open(path, 'rb') as f:
        return pickle.load(f)

def replay_scenario(scenario_path, render=True):
    """Replay a single scenario in MetaDrive."""
    try:
        from metadrive.envs.scenario_env import ScenarioEnv
        from metadrive.policy.replay_policy import ReplayEgoCarPolicy
    except ImportError:
        print("MetaDrive not installed. Install with: pip install metadrive-simulator")
        return
    
    scenario = load_scenario(scenario_path)
    scenario_id = scenario.get('id', 'unknown')
    
    print(f"\nReplaying scenario: {scenario_id}")
    print(f"  Intervention: {scenario.get('metadata', {}).get('intervention', 'N/A')}")
    
    # Create environment
    env = ScenarioEnv({
        "use_render": render,
        "agent_policy": ReplayEgoCarPolicy,
        "data_directory": str(Path(scenario_path).parent),
        "num_scenarios": 1,
        "start_scenario_index": 0,
    })
    
    try:
        obs, info = env.reset()
        done = False
        step = 0
        
        while not done:
            action = [0, 0]  # ReplayPolicy handles actual action
            obs, reward, terminated, truncated, info = env.step(action)
            done = terminated or truncated
            step += 1
            
            if render:
                env.render()
        
        print(f"  Completed: {step} steps")
        
    finally:
        env.close()

def main():
    parser = argparse.ArgumentParser(description="Replay CounterBMT scenarios")
    parser.add_argument("--scenario", type=int, default=None, help="Scenario index to replay")
    parser.add_argument("--render", action="store_true", help="Enable rendering")
    parser.add_argument("--list", action="store_true", help="List available scenarios")
    
    args = parser.parse_args()
    
    if args.list:
        print("Available scenarios:")
        for i, path in enumerate(SCENARIO_FILES):
            scenario = load_scenario(path)
            print(f"  [{i}] {scenario.get('id', 'unknown')}")
            print(f"      Intervention: {scenario.get('metadata', {}).get('intervention', 'N/A')}")
        return
    
    if args.scenario is not None:
        if 0 <= args.scenario < len(SCENARIO_FILES):
            replay_scenario(SCENARIO_FILES[args.scenario], render=args.render)
        else:
            print(f"Invalid scenario index. Available: 0-{len(SCENARIO_FILES)-1}")
    else:
        # Replay all scenarios
        for path in SCENARIO_FILES:
            replay_scenario(path, render=args.render)
            input("Press Enter to continue to next scenario...")

if __name__ == "__main__":
    main()
